/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpusapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nansyiiah
 */
public class EditBukuNovel extends javax.swing.JFrame {

    /**
     * Creates new form EditBukuAdmin
     */
    public Connection conn;
    public ResultSet rs;
    public PreparedStatement pst;
    private String[] data;
    
    public EditBukuNovel() {
        initComponents();
        UpdateTablee();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void UpdateTablee(){
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            String sql = "SELECT * FROM buku_novel where id_buku='"+txt_idbuku.getText()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData md = rs.getMetaData();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//            int columnCount = md.getColumnCount();
//            Vector columnNames = new Vector(columnCount);
            
//            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            
            dtm.setRowCount(0);
            String [] dataa = new String[5];
        int i = 1; 
        
        while(rs.next()){
            
            dataa[0] = rs.getString("id_buku");
            dataa[1] = rs.getString("judul_buku");
            dataa[2] = rs.getString("penulis_buku");
            dataa[3] = rs.getString("tahun_terbit");
            dtm.addRow(dataa);
            i++;
        }
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txt_idbuku = new javax.swing.JTextField();
        tahunterbit = new javax.swing.JTextField();
        simpan = new javax.swing.JLabel();
        judulbuku = new javax.swing.JTextField();
        penulisbuku = new javax.swing.JTextField();
        kembali = new javax.swing.JLabel();
        cari = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_idbuku.setBorder(null);
        jPanel1.add(txt_idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 20));

        tahunterbit.setBorder(null);
        jPanel1.add(tahunterbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 430, 80, 20));

        simpan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                simpanMouseClicked(evt);
            }
        });
        jPanel1.add(simpan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 100, 40));

        judulbuku.setBorder(null);
        jPanel1.add(judulbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 430, 70, 30));

        penulisbuku.setBorder(null);
        jPanel1.add(penulisbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 430, 80, 20));

        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 80, 90, 40));

        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 300, 60, 30));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID Buku", "Judul Buku", "Penulis Buku", "Tahun Terbit"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 350, 320, 50));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/edit buku.png"))); // NOI18N
        jLabel5.setText("jLabel5");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            String sql = "SELECT * FROM buku_novel where id_buku='"+txt_idbuku.getText()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
            ResultSetMetaData md = rs.getMetaData();
            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//            int columnCount = md.getColumnCount();
//            Vector columnNames = new Vector(columnCount);
            
//            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            
            dtm.setRowCount(0);
            String [] dataa = new String[5];
        int i = 1; 
        
        while(rs.next()){
            
            dataa[0] = rs.getString("id_buku");
            dataa[1] = rs.getString("judul_buku");
            dataa[2] = rs.getString("penulis_buku");
            dataa[3] = rs.getString("tahun_terbit");
            judulbuku.setText(rs.getString("judul_buku"));
            penulisbuku.setText(rs.getString("penulis_buku"));
            tahunterbit.setText(rs.getString("tahun_terbit"));
            dtm.addRow(dataa);
            i++;
        }
        
        
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cariMouseClicked

    private void simpanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_simpanMouseClicked
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            String sql = "UPDATE buku_novel SET id_buku='"+txt_idbuku.getText()+"',"+"judul_buku='"+judulbuku.getText()+"',"+"penulis_buku='"+penulisbuku.getText()+"',"+"tahun_terbit='"+tahunterbit.getText()+"' where id_buku="+txt_idbuku.getText()+"";
            Statement stat = conn.createStatement();
            PreparedStatement st = conn.prepareStatement(sql);
            st.executeUpdate();
//            st.executeQuery(sql);
            
//            st.setString(2,judulbuku.getText());
//            st.setString(3,penulisbuku.getText());
//            st.setString(4,tahunterbit.getText());
//            
            JOptionPane.showMessageDialog(null, "Edit buku sukses !");
//            int columnCount = md.getColumnCount();
//            Vector columnNames = new Vector(columnCount);
            
//            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            
            
        
        
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_simpanMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditBukuNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditBukuNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditBukuNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditBukuNovel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditBukuNovel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cari;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField judulbuku;
    private javax.swing.JLabel kembali;
    private javax.swing.JTextField penulisbuku;
    private javax.swing.JLabel simpan;
    private javax.swing.JTextField tahunterbit;
    private javax.swing.JTextField txt_idbuku;
    // End of variables declaration//GEN-END:variables
}
