/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpusapp;

import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author nansyiiah
 */
public class MenuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form MenuAdmin
     */
    public MenuAdmin() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        liat_user = new javax.swing.JLabel();
        buku_komik = new javax.swing.JLabel();
        buku_novel = new javax.swing.JLabel();
        buku_teknologi = new javax.swing.JLabel();
        buku_pengetahuan = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        liat_user.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                liat_userMouseClicked(evt);
            }
        });
        jPanel1.add(liat_user, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 310, 110, 40));

        buku_komik.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_komikMouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                buku_komikMousePressed(evt);
            }
        });
        jPanel1.add(buku_komik, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 380, 100, 60));

        buku_novel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_novelMouseClicked(evt);
            }
        });
        jPanel1.add(buku_novel, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 460, 100, 50));

        buku_teknologi.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_teknologiMouseClicked(evt);
            }
        });
        jPanel1.add(buku_teknologi, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 460, 90, 60));

        buku_pengetahuan.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                buku_pengetahuanMouseClicked(evt);
            }
        });
        jPanel1.add(buku_pengetahuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 390, 90, 50));

        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 84, 90, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/dashboard admin (2).png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buku_komikMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_komikMouseClicked
        try {
            new MenuKomikAdmin().setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buku_komikMouseClicked

    private void buku_komikMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_komikMousePressed
        try {
            new MenuKomikAdmin().setVisible(true);
            dispose();
        } catch (Exception ex) {
            Logger.getLogger(MenuAdmin.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buku_komikMousePressed

    private void liat_userMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_liat_userMouseClicked
        try{
            new LiatUser().setVisible(true);
            dispose();
        }catch(Exception ex){
            System.out.println("Error : "+ ex);
        }
    }//GEN-LAST:event_liat_userMouseClicked

    private void buku_novelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_novelMouseClicked
        new MenuNovelAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_buku_novelMouseClicked

    private void buku_pengetahuanMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_pengetahuanMouseClicked
        // TODO add your handling code here:
        new MenuIlmuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_buku_pengetahuanMouseClicked

    private void buku_teknologiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_buku_teknologiMouseClicked
        // TODO add your handling code here:
        new MenuTeknologiAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_buku_teknologiMouseClicked

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        new Utama().setVisible(true);
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MenuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel buku_komik;
    private javax.swing.JLabel buku_novel;
    private javax.swing.JLabel buku_pengetahuan;
    private javax.swing.JLabel buku_teknologi;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel liat_user;
    // End of variables declaration//GEN-END:variables
}
