/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package perpusapp;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author nansyiiah
 */
public class DeleteBukuTeknologi extends javax.swing.JFrame {

    /**
     * Creates new form DeleteBuku
     */
    public Connection conn;
    public ResultSet rs;
    public PreparedStatement pst;
    private String[] data;
    public DeleteBukuTeknologi() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        kembali = new javax.swing.JLabel();
        judulbuku = new javax.swing.JLabel();
        penulisbuku = new javax.swing.JLabel();
        tahunterbit = new javax.swing.JLabel();
        hapus = new javax.swing.JLabel();
        cari = new javax.swing.JLabel();
        idbuku = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        kembali.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                kembaliMouseClicked(evt);
            }
        });
        jPanel1.add(kembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 84, 70, 30));
        jPanel1.add(judulbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 390, 70, 30));
        jPanel1.add(penulisbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 390, 70, 30));
        jPanel1.add(tahunterbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 390, 70, 30));

        hapus.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                hapusMouseClicked(evt);
            }
        });
        jPanel1.add(hapus, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 500, 100, 30));

        cari.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                cariMouseClicked(evt);
            }
        });
        cari.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cariKeyPressed(evt);
            }
        });
        jPanel1.add(cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 290, 80, 50));

        idbuku.setBorder(null);
        jPanel1.add(idbuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, 70, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/assets/delete buku.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 450, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void kembaliMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kembaliMouseClicked
        // TODO add your handling code here:
        new MenuAdmin().setVisible(true);
        dispose();
    }//GEN-LAST:event_kembaliMouseClicked

    private void cariMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_cariMouseClicked
        // TODO add your handling code here:
            try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            String sql = "SELECT * FROM buku_teknologi where id_buku='"+idbuku.getText()+"'";
            pst = conn.prepareStatement(sql);
            rs = pst.executeQuery();
//            ResultSetMetaData md = rs.getMetaData();
//            DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();
//            int columnCount = md.getColumnCount();
//            Vector columnNames = new Vector(columnCount);
            
//            DefaultTableModel model = new DefaultTableModel(columnNames, 0);
            
//            dtm.setRowCount(0);
            String [] dataa = new String[99];
        int i = 1; 
        
        while(rs.next()){
            
            dataa[0] = rs.getString("id_buku");
            dataa[1] = rs.getString("judul_buku");
            dataa[2] = rs.getString("penulis_buku");
            dataa[3] = rs.getString("tahun_terbit");
            judulbuku.setText(rs.getString("judul_buku"));
            penulisbuku.setText(rs.getString("penulis_buku"));
            tahunterbit.setText(rs.getString("tahun_terbit"));
//            dtm.addRow(dataa);
            i++;
        }
        
        
        }catch(SQLException e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cariMouseClicked

    private void hapusMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_hapusMouseClicked
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            Statement stat = conn.createStatement();
            String sql = "delete from buku_teknologi where id_buku='"+idbuku.getText()+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Delete buku sukses ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_hapusMouseClicked

    private void cariKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cariKeyPressed
        // TODO add your handling code here:
        try{
            conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/perpus_pbo", "root", "");
            Statement stat = conn.createStatement();
            String sql = "delete from buku_teknologi where id_buku='"+idbuku.getText()+"'";
            stat.executeUpdate(sql);
            JOptionPane.showMessageDialog(null, "Delete buku sukses ");
        }catch(Exception e){
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_cariKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DeleteBukuTeknologi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DeleteBukuTeknologi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DeleteBukuTeknologi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DeleteBukuTeknologi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DeleteBukuTeknologi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel cari;
    private javax.swing.JLabel hapus;
    private javax.swing.JTextField idbuku;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel judulbuku;
    private javax.swing.JLabel kembali;
    private javax.swing.JLabel penulisbuku;
    private javax.swing.JLabel tahunterbit;
    // End of variables declaration//GEN-END:variables
}
